language: d
sudo: false

matrix:
  include:
    - d: dmd
      env: MODEL=64
    - d: dmd-nightly
      env: MODEL=64
    - d: dmd
      env: MODEL=32
      addons:
        apt:
          packages:
            - g++-multilib
            - libcurl4-openssl-dev:i386
    - d: dmd-nightly
      env: MODEL=32
      addons:
        apt:
          packages:
            - g++-multilib
            - libcurl4-openssl-dev:i386

script:
  - ./travis.sh
