language: d
d:
  - dmd
sudo: false

matrix:
  include:
    - env: MODEL=64
    - env: MODEL=32
      addons:
        apt:
          packages:
            - g++-multilib
            - libcurl4-openssl-dev:i386

script:
  - ./travis.sh
